### ISSUE TITLE
请问一下大佬还在维护嘛，有没有考虑支持pwa

### ISSUE THREAD

**Issue by xiyuvi** [airene/vitepress-blog-pure#1]

**Comment by airene** [comment]
pwa 有场景么，感觉没啥用啊，而且 vite是不是改改就能支持啊？

**Comment by xiyuvi** [comment]
感谢回复，我想到的场景是：在手机上可以把网站保存为一个桌面图标，然后打开。感觉还挺酷的。
![image](https://user-images.githubusercontent.com/38217058/167575930-ae2cd221-cd4c-43d3-9ced-7c436ba0403a.png)

![image](https://user-images.githubusercontent.com/38217058/167576323-57335784-82ee-4efc-b9a9-85f3b32b1d95.png)

我是萌新，刚刚搜了一下有vite一键支持pwa的插件，但是我不清楚vitepress能不能直接配置就用
