### ISSUE TITLE
使用侧边栏导致导航栏显示异常

### ISSUE THREAD

**Issue by Zolyn** [airene/vitepress-blog-pure#11]
![image](https://user-images.githubusercontent.com/35414841/195875785-9634d0d7-24f1-4d3f-8071-8e395a64e9f5.png)

如图所示

重现方法：
1. 克隆[重现仓库](https://github.com/Zolyn/Paracosm)，运行`npm run dev`查看
2. 在本项目配置文件中添加`themeConfig.sidebar`项，内容为如下：

```javascript
sidebar: [
    {
        text: 'Test',
        items: [
            {
                text: 'Test',
                link: '/posts/vitepress-first'
            }
        ]
    }
],
```

**Comment by airene** [comment]
侧边栏被用作 文章摘要了，比如https://www.xining.me/posts/vite_dev_ui_optimize.html 这种的右边。
所以本项目的非posts（非博文，就是pages）都是关闭sidebar的， 站点主导航是由上面的navbar来实现。
