### ISSUE TITLE
你好，我想问一下如何开启搜索功能，配置了不生效

### ISSUE THREAD

**Issue by huoranger** [airene/vitepress-blog-pure#12]
![image](https://user-images.githubusercontent.com/67517385/204159382-bdf5ae48-9be1-4120-ba5e-b4bcda1ad736.png)

**Comment by airene** [comment]
你放的位置不对吧 放这个下面试试 themeConfig
搜索的我没做任何修改
参考配置
https://github.com/vuejs/vitepress/blob/main/docs/.vitepress/config.ts
