### ISSUE TITLE
是否考虑集成自动化部署？

### ISSUE THREAD

**Issue by mono2048** [airene/vitepress-blog-pure#13]
部署方案：
https://github.com/dadaiwei/fe-deploy-cli
我的blog:
http://www.mono2048.site/

**Comment by airene** [comment]
有点意思， 你这个感觉适合vps配置比较低的，不想在上面装编译环境的。 本机打包好上传，不过看出来需要怎么集成啊？看了一下不是纯工具向的么？
目前比较多的使用场景是github action & github pages

**Comment by mono2048** [comment]
的确是纯工具向的，我是上传到了服务器nginx代理的目录。集成的话把工具的添加为开发依赖，配置`npm deploy`脚本。
顺便说一句：github action & github pages我还不会。

**Comment by airene** [comment]
> 的确是纯工具向的，我是上传到了服务器nginx代理的目录。集成的话把工具的添加为开发依赖，配置`npm deploy`脚本。 顺便说一句：github action & github pages我还不会。

嗯嗯，了解一下，这两个东西，后面的很简单 就是一个“免费空间”，有自己的规则，顺便说一下 github.io 是和com.cn一样，{长的比较奇怪实际是顶级域名，这个有点不是很好理解} ,github actions比较强大，类似jenkins 可能比jenkins还强大，可以了解一下，当前算比较流行了
