### ISSUE TITLE
期望加入404页面的自定义

### ISSUE THREAD

**Issue by admin8756** [airene/vitepress-blog-pure#17]
我看了文档没有找到404页面的相关定义。大佬知道吗

**Comment by airene** [comment]
https://vitepress.dev/guide/custom-theme#building-a-layout
这里有点介绍，我发现在本地pnpm run dev 模式，输入一个不存在的url能到404
类似访问 https://vitepress.dev/guide/deploysadf 官方的这样的不存在的页面，
但是build上线之后部署在nginx下这个特性就没了，直接无法访问，有可能和部署方式有关系
不过什么场景用到404啊，不都是链接点着看么？
你先看看，如果不行，我找时间看看。

**Comment by airene** [comment]
提交可以啊， 你搜搜怎么pull request就行，
个性化方面可以走fork，然后维护自己的版本
------
404的问题，你可以试试纯官方的版本编译完放nginx 404能不能正常工作么？ ：）

**Comment by airene** [comment]
> > ## 提交可以啊， 你搜搜怎么pull request就行，
> > 个性化方面可以走fork，然后维护自己的版本
> > 404的问题，你可以试试纯官方的版本编译完放nginx 404能不能正常工作么？ ：）
> 
> 404这样处理太呆了！。我试试官方的那个方法吧。判断pagedata

对 就是纯官方版本，加点文章然后build 直接放nginx下，看看404是不是正常工作。

test.jpg图片是之前处理 https://github.com/airene/vitepress-blog-pure/issues/7 这个问题加的
