### ISSUE TITLE
发现两个样式的小问题，麻烦修改一下

### ISSUE THREAD

**Issue by xiyuvi** [airene/vitepress-blog-pure#2]
我发现有两个样式的小问题，麻烦您修改一下
第一个：底部宽度超长出现横向滚动条
.site-footer {
  width: 100vw;
}
改成
.site-footer {
  width: 100%;
}
原样式在博客名称过长的情况下会引起 site-footer超长，出现横向滚动条，如下图所示。
![图片](https://user-images.githubusercontent.com/38217058/168121226-005f0911-1696-4fb1-88c4-eb79b9782e2a.png)
第二个：正文内容会被右侧的标题挡住

@media screen and (min-width: 720px) {}中添加
 .page {
       
        width: calc(100% - 244px);
    }

原样式正文部分内容在电脑小窗口下会被右侧标题挡住，页面宽度接近720px的极限情况下甚至会被挡住一半正文，如下图所示。
![图片](https://user-images.githubusercontent.com/38217058/168122548-b7177c70-f907-4479-98a4-bbee106caecc.png)

**Comment by xiyuvi** [comment]
第二个样式更改后有bug，会导致首页内容也左移。还要再改一下。
![image](https://user-images.githubusercontent.com/38217058/168201970-fd870b57-877c-460f-9e24-0fbca5da2ecb.png)

**Comment by airene** [comment]
好的， 第一个怎么复现啊，我试试，改成100% 可能移动端没准有问题，
第二个问题，可以改成如果宽度太小了，就直接隐藏右侧的导航好了， 等第一个复现了 一起修复一下。

**Comment by xiyuvi** [comment]
> 啊，我第一次尝试，改成可能没准时有， 第二个移动端问题，可以改成如果太小了，就很好10%直接出现问题的导航好，等第一个复现了一起修复一下。

第一个问题，您把您的博客名称改成四个汉字就可以复现了。或者进入这个测试网站 pt.xiyu.pro 把底部的样式改成100vw也可以反向复现。
![image](https://user-images.githubusercontent.com/38217058/168213759-2224c703-c773-4f6f-9001-35526974ea80.png)

**Comment by airene** [comment]
两个问题都改好了 你试试 https://github.com/airene/vitepress-blog-pure/commit/47d8473508c5d7f8332928f49400eaee6fa331fd 修改前两个文件就行

**Comment by xiyuvi** [comment]
> 两个都改好你试试[47d8473](https://github.com/airene/vitepress-blog-pure/commit/47d8473508c5d7f8332928f49400eaee6fa331fd)修改前两个文件就行了

我晚上回去试一试，我觉得您可以在项目介绍里放个赞赏码

**Comment by xiyuvi** [comment]
> 两个问题都改好了 你试试 [47d8473](https://github.com/airene/vitepress-blog-pure/commit/47d8473508c5d7f8332928f49400eaee6fa331fd) 修改前两个文件就行

改完就好了，谢谢
