### ISSUE TITLE
vitepress正式版已发布了。

### ISSUE THREAD

**Issue by haskio** [airene/vitepress-blog-pure#20]
vitepress正式版已发布了，该主题可以直接用在正式版上面吗？

**Comment by airene** [comment]
直接npm安装可能要等一等，直接用没问题。最近有一个小伙提了pull request 我合进来了， 可能稍微需要点修改再用比较好 握手

**Comment by airene** [comment]
按照readme使用没问题，可以直接看ti.bi, 😊

**Comment by haskio** [comment]
握手，这就去开干。
