### ISSUE TITLE
rendering pages...ReferenceError: location is not defined

### ISSUE THREAD

**Issue by haskio** [airene/vitepress-blog-pure#21]
请教一下build的时候提示 ：rendering pages...ReferenceError: location is not defined

用的copy方式，node版本16。
详情如下：
![image](https://github.com/airene/vitepress-blog-pure/assets/2170753/a6951496-2379-4f5b-bb30-2e4812b97590)

但是文件又可以正常生成。

**Comment by airene** [comment]
可以了 看：https://github.com/airene/vitepress-blog-pure/commit/57daf8ece818ace4301082767b8e2cb923125339 location属于浏览器的属性

**Comment by haskio** [comment]
已经更新了。
