### ISSUE TITLE
移动端搜索结果，文字行高需要调整

### ISSUE THREAD

**Issue by Haku96** [airene/vitepress-blog-pure#24]
![image](https://github.com/airene/vitepress-blog-pure/assets/28948821/cc9f3c7f-61dd-470a-993e-288142c4b127)

**Comment by airene** [comment]
收到，删除custom.css中的 .title这个样式就好
see https://github.com/airene/vitepress-blog-pure/commit/c48282ecd7008625f7f72f7b87494e4387ec5657#diff-6fc5541ea9ddbfc835353cd2dafac13a76e68f7713c81f63d94fc98eca52669d
