### ISSUE TITLE
可以给文章里的a链接添加一个border-bottom来指示链接吗

### ISSUE THREAD

**Issue by xiyuvi** [airene/vitepress-blog-pure#3]
可以给文章里的a链接添加一个border-bottom来指示链接吗，或者用其他什么样式区分一下。
现在是链接和文字没有区分，不太容易知道那个是可点击的链接

md内容：

 [点击下载](https://github.com/ianespana/ShawzinBot)

现在的样子：
![火狐截图_2022-05-14T05-48-29 585Z](https://user-images.githubusercontent.com/38217058/168412635-6eba275c-df81-4322-b5f0-95df6dea26da.png)

加了边框的样子：
![火狐截图_2022-05-14T05-47-59 627Z](https://user-images.githubusercontent.com/38217058/168412621-88469bba-f09a-4beb-88ba-34fd8b3e2fa8.png)

我个人觉得这样更明显提示链接跳转，您觉得有必要添加吗

**Comment by airene** [comment]
可以啊， 可以加一个颜色，和主题色一致的，

**Comment by xiyuvi** [comment]
> 可以啊， 可以加一个颜色，和主题色一致的，

那麻烦您有空了看一下，我想直接给文章的a标签加样式就好了，结果愣是没找到主页和文字的父级css有什么不同 0.0 为了怕污染主页就没改

**Comment by airene** [comment]
https://github.com/airene/vitepress-blog-pure/commit/ff1176fa20b590921b03806c54e841a3f0ea3515 这样就可以了， 应该不是影响其他的内容，我看了起码不影响 archives里的链接

**Comment by airene** [comment]
added the furture
