### ISSUE TITLE
Support for Light / Dark Mode?

### ISSUE THREAD

**Issue by richardzone** [airene/vitepress-blog-pure#6]
The latest VitePress added light / dark mode switch for themes. 

Is there any plan to support dark theme? The current style need some minor tweaks and the Comment component needs adjustment as well (it's github-light by default)

**Comment by airene** [comment]
thanks for using, yes,from now vitepress version is alpha.4,my plan is get anthor round dev after beta or rc version.

**Comment by richardzone** [comment]
Sounds good to me! @airene Thank you for this awesome theme!

**Comment by fzdwx** [comment]
可以，很期待，应该快了。

**Comment by airene** [comment]
是的，已经到alpha13了，不严格的到beta，怕走弯路的话 到rc肯定可以动手了。

**Comment by airene** [comment]
I have update this theme to vitepress [1.0.0-alpha.15], bring the dark mode,and I think this is the first version about color,I'll adjust them soon for my favior.
已经升级到目前最新的1.0.0-alpha.15，并且已经支持第一版 黑色模式，不过黑色模式不是很满意，可能稍后会微调。
具体方法请看提交的文件差异 
see this https://github.com/airene/vitepress-blog-pure/commit/77e832fb50fd732c6dbd6466c1acbe86aafeb29d

**Comment by fzdwx** [comment]
加油
