### ISSUE TITLE
Use Image in Description

### ISSUE THREAD

**Issue by richardzone** [airene/vitepress-blog-pure#7]
Is there a way to use image in description to display in `index.md`? For example:

```
---
date: 2022-08-10
title: My Awesome Post
description: Awesome Photo here: ![Photo](/public/images/Awesome_photo.png)
---

# {{ $frontmatter.title }}

TODO
```

Hopefully this can be supported when Vitepress turns 1.0.

**Comment by airene** [comment]
I think this feature has no relation about vitepress,  maybe about grap-matter lib,  anyway you can get it by these step.
[change list](https://github.com/airene/vitepress-blog-pure/commit/dde175b9b0a0d6900a57271a44cc36e58de65c47)

1. replace the file `.vitepress/theme/components/Page.vue` 
2. write description like this : <img src="/test.jpg" width="100%" /> <br> It's a test

ps: 
     1.  I did't know if you know html, if you don't, I,ll take a detail desc.
     2.  image file path is in the public folder.   There is a favicon.ico in it.
     3. `<br> It's a test` is just for after the image maybe some summary in there
    
 I'm sorry for my poor English

**Comment by richardzone** [comment]
Your English is perfectly fine - thank you for helping out!
