### ISSUE TITLE
留言系统可以推荐 这个GO语言写的 “Artalk” 轻量、安全、易上手的自托管评论系统

### ISSUE THREAD

**Issue by xiamuguizhi** [airene/vitepress-blog-pure#8]
地址： https://artalk.js.org/

VuePress[#](https://artalk.js.org/guide/frontend/import-blog.html#vuepress)
以 [VuePress v2](https://github.com/vuepress/vuepress-next) 为例，继承默认主题 @vuepress/theme-default

可参考：[“/.vuepress/theme/Artalk.vue”](https://github.com/ArtalkJS/Docs/blob/eef37bca8cc0c9973bf121fdef4014dcd940f104/docs/.vuepress/theme/Artalk.vue) 创建 Artalk 评论组件。

https://artalk.js.org/guide/frontend/import-blog.html#vuepress

**Comment by airene** [comment]
谢谢你的建议，在vps廉价的时候倒是可以考虑，坦白讲需要self-hosted来说，还是有点成本的，ha和使用方面都会增加，这就有点打破可以放在各种pages服务就能转的特点。
artalk这个项目我+ star了，看看后续发展吧

**Comment by xiamuguizhi** [comment]
@airene 是不是每次 新增文章 都要关闭 一次 服务 重新 npm run dev ... 我以为直接新增文章  首页就会显示的  哈哈 可能是我想多了。

**Comment by airene** [comment]
嗯，我有vps 只是说对用户而言门槛不一样哈
